package com.xukaiqiang.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-12-16T18:42:51.711+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://webservice.xukaiqiang.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "say", targetNamespace = "http://webservice.xukaiqiang.com/", className = "com.xukaiqiang.webservice.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://webservice.xukaiqiang.com/", className = "com.xukaiqiang.webservice.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
